//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaerskLine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public int CustomerID { get; set; }
        public int CargoID { get; set; }
        public int ShipID { get; set; }
        public int WarehouseID { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Ship Ship { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
